// The single source of truth for everything on the site.
// Adding content = one entry here + one module in src/topics/ (or one HTML
// file in articles/ for type 'article'). Homepage search indexes title,
// summary, category, tags, and searchText.

export const categories = [
  'Data Structures',
  'Sorting',
  'Searching',
  'Concepts',
  'Systems',
  'AI & ML',
  'Papers',
];

// Entries may declare `buildsOn: [ids]` — the simpler ideas they are made of.
// Topic pages render these as "Built from" links, and compute the reverse
// ("Next up") automatically, so complex topics always point back to their
// ingredients and simple topics advertise what they unlock.

export const topics = [
  {
    id: 'linked-list',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Linked List',
    summary: 'A chain of nodes connected by pointers — append, search, and remove by re-linking.',
    tags: ['pointers', 'nodes', 'traversal'],
    module: () => import('./topics/linked-list.js'),
  },
  {
    id: 'stack',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Stack',
    summary: 'Last In, First Out: push and pop from the top, the way undo history works.',
    tags: ['LIFO', 'push', 'pop'],
    module: () => import('./topics/stack.js'),
  },
  {
    id: 'queue',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Queue',
    summary: 'First In, First Out: enqueue at the back, dequeue from the front, like a line at a store.',
    tags: ['FIFO', 'enqueue', 'dequeue'],
    module: () => import('./topics/queue.js'),
  },
  {
    id: 'hash-table',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Hash Table',
    summary: 'Turn a key into a bucket index, handle collisions with probing, rehash as it fills.',
    tags: ['hashing', 'collisions', 'linear probing', 'load factor', 'rehash'],
    module: () => import('./topics/hash-table.js'),
  },
  {
    id: 'binary-search-tree',
    type: 'visualization',
    buildsOn: ['binary-search'],
    category: 'Data Structures',
    title: 'Binary Search Tree',
    summary: 'Smaller values go left, larger go right — so lookups skip half the tree at every node.',
    tags: ['BST', 'tree', 'insert', 'search'],
    module: () => import('./topics/binary-search-tree.js'),
  },
  {
    id: 'insertion-sort',
    type: 'visualization',
    category: 'Sorting',
    title: 'Insertion Sort',
    summary: 'Slide each value left into its place in a growing sorted prefix, like sorting cards in your hand.',
    tags: ['sorting', 'nearly sorted', 'O(n^2)', 'adaptive'],
    module: () => import('./topics/insertion-sort.js'),
  },
  {
    id: 'selection-sort',
    type: 'visualization',
    category: 'Sorting',
    title: 'Selection Sort',
    summary: 'Scan for the smallest remaining value and swap it into place — minimum swaps, maximum scanning.',
    tags: ['sorting', 'minimum', 'O(n^2)'],
    module: () => import('./topics/selection-sort.js'),
  },
  {
    id: 'avl-tree',
    type: 'visualization',
    buildsOn: ['binary-search-tree', 'b-tree'],
    category: 'Data Structures',
    title: 'AVL Tree Rotations',
    summary: 'Self-balancing in action: balance factors hit ±2 and rotations repair the tree on the spot.',
    tags: ['AVL', 'self-balancing', 'rotations', 'balance factor', 'red-black'],
    module: () => import('./topics/avl-tree.js'),
  },
  {
    id: 'tree-traversals',
    type: 'visualization',
    buildsOn: ['binary-search-tree', 'recursion', 'queue'],
    category: 'Data Structures',
    title: 'Tree Traversals',
    summary: 'In-order, pre-order, post-order, and level-order — four ways to walk a tree, each with a job.',
    tags: ['BFS', 'DFS', 'in-order', 'level-order', 'tree'],
    module: () => import('./topics/tree-traversals.js'),
  },
  {
    id: 'binary-heap',
    type: 'visualization',
    buildsOn: ['binary-search-tree'],
    category: 'Data Structures',
    title: 'Binary Heap (Priority Queue)',
    summary: 'A tree where every parent beats its children — the maximum is always one peek away.',
    tags: ['priority queue', 'heap', 'bubble up', 'sift down'],
    module: () => import('./topics/binary-heap.js'),
  },
  {
    id: 'b-tree',
    type: 'visualization',
    buildsOn: ['binary-search-tree', 'binary-search'],
    category: 'Data Structures',
    title: 'B-Trees (How Databases Read)',
    summary: 'Nodes hold multiple keys and split upward as they fill — the index behind Postgres and MySQL.',
    tags: ['b-tree', 'database index', 'postgres', 'mysql', 'disk', 'balanced'],
    module: () => import('./topics/b-tree.js'),
  },
  {
    id: 'trie',
    type: 'visualization',
    buildsOn: ['hash-table', 'tree-traversals'],
    category: 'Data Structures',
    title: 'Trie (Prefix Tree)',
    summary: 'Words stored letter by letter, prefixes shared — autocomplete is just a subtree walk.',
    tags: ['trie', 'autocomplete', 'prefix', 'search suggestions', 'IP routing'],
    module: () => import('./topics/trie.js'),
  },
  {
    id: 'topological-sort',
    type: 'visualization',
    buildsOn: ['graph-bfs', 'queue'],
    category: 'Data Structures',
    title: 'Topological Sort',
    summary: 'Order tasks so every prerequisite comes first — and detect circular dependencies for free.',
    tags: ['DAG', 'kahn', 'build order', 'dependencies', 'npm', 'airflow'],
    module: () => import('./topics/topological-sort.js'),
  },
  {
    id: 'union-find',
    type: 'visualization',
    buildsOn: ['tree-traversals'],
    category: 'Data Structures',
    title: 'Union-Find (Disjoint Sets)',
    summary: 'Merge groups and test connectivity in near-constant time — parent pointers plus two sly tricks.',
    tags: ['disjoint sets', 'kruskal', 'connectivity', 'path compression', 'inverse ackermann'],
    module: () => import('./topics/union-find.js'),
  },
  {
    id: 'skip-list',
    type: 'visualization',
    buildsOn: ['linked-list', 'binary-search'],
    category: 'Data Structures',
    title: 'Skip List',
    summary: 'A linked list with probabilistic express lanes — O(log n) search without any rebalancing.',
    tags: ['skip list', 'redis', 'probabilistic', 'sorted set', 'express lanes'],
    module: () => import('./topics/skip-list.js'),
  },
  {
    id: 'graph-bfs',
    type: 'visualization',
    buildsOn: ['queue', 'tree-traversals'],
    category: 'Data Structures',
    title: 'Graph BFS',
    summary: 'Explore a graph in expanding rings with a queue — the fewest-hops path falls out for free.',
    tags: ['graph', 'breadth-first', 'shortest path', 'network'],
    module: () => import('./topics/graph-bfs.js'),
  },
  {
    id: 'dijkstra',
    type: 'visualization',
    buildsOn: ['graph-bfs', 'binary-heap'],
    category: 'Data Structures',
    title: "Dijkstra's Shortest Path",
    summary: 'Find the cheapest route in a weighted graph by always expanding the cheapest known node.',
    tags: ['graph', 'shortest path', 'GPS', 'greedy', 'weighted'],
    module: () => import('./topics/dijkstra.js'),
  },
  {
    id: 'a-star',
    type: 'visualization',
    buildsOn: ['dijkstra'],
    category: 'Data Structures',
    title: 'A* Search',
    summary: 'Shortest path with a compass: expand by g + h, and skip everything pointing away from the goal.',
    tags: ['pathfinding', 'heuristic', 'games', 'GPS', 'graph'],
    module: () => import('./topics/a-star.js'),
  },
  {
    id: 'kruskal-mst',
    type: 'visualization',
    buildsOn: ['union-find', 'dijkstra', 'binary-heap'],
    category: 'Data Structures',
    title: "Kruskal's Minimum Spanning Tree",
    summary: 'Connect every node at minimum total cost: cheapest edges first, cycles vetoed by Union-Find.',
    tags: ['MST', 'kruskal', 'greedy', 'clustering', 'network design'],
    module: () => import('./topics/kruskal-mst.js'),
  },
  {
    id: 'prims-mst',
    type: 'visualization',
    buildsOn: ['kruskal-mst', 'binary-heap', 'dijkstra'],
    category: 'Data Structures',
    title: "Prim's Algorithm",
    summary: 'Grow one tree outward, always crossing the frontier on the cheapest edge — the MST, built the other way.',
    tags: ['MST', 'prim', 'greedy', 'frontier', 'priority queue'],
    module: () => import('./topics/prims-mst.js'),
  },
  {
    id: 'bubble-sort',
    type: 'visualization',
    category: 'Sorting',
    title: 'Bubble Sort',
    summary: 'Compare neighbors and swap — the largest value bubbles to the end on every pass.',
    tags: ['sorting', 'swaps', 'O(n^2)'],
    module: () => import('./topics/bubble-sort.js'),
  },
  {
    id: 'merge-sort',
    type: 'visualization',
    buildsOn: ['recursion'],
    category: 'Sorting',
    title: 'Merge Sort',
    summary: 'Split the array in half, sort each half, then merge — divide and conquer at O(n log n).',
    tags: ['sorting', 'divide and conquer', 'stable', 'O(n log n)'],
    module: () => import('./topics/merge-sort.js'),
  },
  {
    id: 'quick-sort',
    type: 'visualization',
    buildsOn: ['recursion'],
    category: 'Sorting',
    title: 'Quick Sort',
    summary: 'Pick a pivot, partition the array around it, recurse — fast in practice and in place.',
    tags: ['sorting', 'pivot', 'partition', 'recursion'],
    module: () => import('./topics/quick-sort.js'),
  },
  {
    id: 'heap-sort',
    type: 'visualization',
    buildsOn: ['binary-heap'],
    category: 'Sorting',
    title: 'Heap Sort',
    summary: 'Build a max-heap inside the array, then repeatedly move the largest value to the end.',
    tags: ['sorting', 'heap', 'sift down', 'O(n log n)'],
    module: () => import('./topics/heap-sort.js'),
  },
  {
    id: 'linear-search',
    type: 'visualization',
    category: 'Searching',
    title: 'Linear Search',
    summary: 'Check every element from left to right — simple, and the best you can do unsorted.',
    tags: ['search', 'O(n)'],
    module: () => import('./topics/linear-search.js'),
  },
  {
    id: 'binary-search',
    type: 'visualization',
    category: 'Searching',
    title: 'Binary Search',
    summary: 'Halve the search range on every comparison — find anything in a sorted array in O(log n).',
    tags: ['search', 'sorted', 'O(log n)', 'divide and conquer'],
    module: () => import('./topics/binary-search.js'),
  },
  {
    id: 'recursion',
    type: 'visualization',
    category: 'Concepts',
    title: 'Recursion',
    summary: 'Watch a function call itself: the call tree for factorial and Fibonacci, opening and returning.',
    tags: ['call stack', 'base case', 'fibonacci', 'factorial'],
    module: () => import('./topics/recursion.js'),
  },
  {
    id: 'big-o-growth',
    type: 'visualization',
    category: 'Concepts',
    title: 'Big-O Growth Rates',
    summary: 'Watch log n, n, n log n, and n² grow apart — the chart that explains why algorithms matter.',
    tags: ['complexity', 'big-o', 'performance', 'scaling'],
    module: () => import('./topics/big-o-growth.js'),
  },
  {
    id: 'reservoir-sampling',
    type: 'visualization',
    buildsOn: ['sliding-window'],
    category: 'Concepts',
    title: 'Reservoir Sampling',
    summary: 'A fair sample from an endless stream in k slots of memory — the probability balances itself.',
    tags: ['streaming', 'sampling', 'probability', 'big data', 'algorithm R'],
    module: () => import('./topics/reservoir-sampling.js'),
  },
  {
    id: 'ab-testing',
    type: 'visualization',
    buildsOn: ['reservoir-sampling', 'value-iteration'],
    category: 'Concepts',
    title: 'A/B Testing & p-values',
    summary: 'Same conversion rates, two sample sizes — watch "obviously better" turn into noise, and back into signal.',
    tags: ['statistics', 'p-value', 'experiments', 'significance', 'product'],
    module: () => import('./topics/ab-testing.js'),
  },
  {
    id: 'binary-exponentiation',
    type: 'visualization',
    buildsOn: ['recursion', 'big-o-growth'],
    category: 'Concepts',
    title: 'Binary Exponentiation',
    summary: 'Square-and-multiply along the exponent bits — huge powers in O(log n) steps instead of n.',
    tags: ['exponentiation', 'RSA', 'modular arithmetic', 'square and multiply', 'cryptography'],
    module: () => import('./topics/binary-exponentiation.js'),
  },
  {
    id: 'edit-distance',
    type: 'visualization',
    buildsOn: ['memoization', 'two-pointers'],
    category: 'Concepts',
    title: 'Edit Distance (DP Table)',
    summary: 'Fill a grid of subproblems and the spell-checker question answers itself in the corner.',
    tags: ['dynamic programming', 'levenshtein', 'spell check', 'diff', 'alignment'],
    module: () => import('./topics/edit-distance.js'),
  },
  {
    id: 'finite-state-machine',
    type: 'visualization',
    buildsOn: ['graph-bfs', 'trie'],
    category: 'Concepts',
    title: 'Finite State Machines',
    summary: 'Walk a DFA matching the pattern ab*c, one character per step — regex demystified.',
    tags: ['FSM', 'DFA', 'regex', 'automata', 'lexer', 'TCP'],
    module: () => import('./topics/finite-state-machine.js'),
  },
  {
    id: 'huffman-coding',
    type: 'visualization',
    buildsOn: ['binary-heap', 'trie', 'tree-traversals'],
    category: 'Concepts',
    title: 'Huffman Coding',
    summary: 'Build the optimal prefix code by always merging the two rarest symbols — compression from a greedy loop.',
    tags: ['compression', 'huffman', 'zip', 'greedy', 'prefix code', 'entropy'],
    module: () => import('./topics/huffman-coding.js'),
  },
  {
    id: 'entropy',
    type: 'visualization',
    buildsOn: ['huffman-coding', 'softmax-temperature', 'gradient-descent'],
    category: 'Concepts',
    title: 'Entropy & Information',
    summary: 'Information = surprise = −log p. From coin flips to compression floors to the LLM training loss.',
    tags: ['entropy', 'information theory', 'shannon', 'cross-entropy', 'perplexity', 'KL divergence'],
    module: () => import('./topics/entropy.js'),
  },
  {
    id: 'two-pointers',
    type: 'visualization',
    buildsOn: ['binary-search'],
    category: 'Concepts',
    title: 'Two Pointers',
    summary: 'Find a pair summing to a target in one pass — squeeze from both ends of a sorted array.',
    tags: ['technique', 'pair sum', 'O(n)', 'interview'],
    module: () => import('./topics/two-pointers.js'),
  },
  {
    id: 'sliding-window',
    type: 'visualization',
    buildsOn: ['two-pointers'],
    category: 'Concepts',
    title: 'Sliding Window',
    summary: 'Find the longest run under a budget in one pass — grow the window right, shrink it left.',
    tags: ['sliding window', 'technique', 'O(n)', 'TCP', 'substring'],
    module: () => import('./topics/sliding-window.js'),
  },
  {
    id: 'memoization',
    type: 'visualization',
    buildsOn: ['recursion', 'hash-table'],
    category: 'Concepts',
    title: 'Memoization (Dynamic Programming)',
    summary: 'Cache every answer the first time you compute it — watch the exponential call tree collapse.',
    tags: ['dynamic programming', 'cache', 'fibonacci', 'optimization'],
    module: () => import('./topics/memoization.js'),
  },
  {
    id: 'lru-cache',
    type: 'visualization',
    buildsOn: ['hash-table', 'linked-list'],
    category: 'Systems',
    title: 'LRU Cache',
    summary: 'Keep the hottest items, evict the least-recently-used — hash table + linked list, fused.',
    tags: ['cache', 'eviction', 'O(1)', 'redis', 'systems design'],
    module: () => import('./topics/lru-cache.js'),
  },
  {
    id: 'load-balancer',
    type: 'visualization',
    buildsOn: ['queue', 'hash-table'],
    category: 'Systems',
    title: 'Load Balancer',
    summary: 'Route incoming requests across servers — round-robin vs least-connections, on identical traffic.',
    tags: ['systems design', 'round robin', 'scaling', 'nginx', 'distributed systems'],
    module: () => import('./topics/load-balancer.js'),
  },
  {
    id: 'consistent-hashing',
    type: 'visualization',
    buildsOn: ['hash-table'],
    category: 'Systems',
    title: 'Consistent Hashing',
    summary: 'Hash servers AND keys onto a ring — adding a server moves only its neighbors, not everything.',
    tags: ['cassandra', 'dynamodb', 'distributed systems', 'ring', 'sharding'],
    module: () => import('./topics/consistent-hashing.js'),
  },
  {
    id: 'lsm-tree',
    type: 'visualization',
    buildsOn: ['merge-sort', 'bloom-filter', 'binary-search'],
    category: 'Systems',
    title: 'LSM Trees (How Cassandra Writes)',
    summary: 'Writes land in a memtable, flush to immutable sorted files, and merge in the background.',
    tags: ['cassandra', 'rocksdb', 'database', 'storage engine', 'write path'],
    module: () => import('./topics/lsm-tree.js'),
  },
  {
    id: 'write-ahead-log',
    type: 'visualization',
    buildsOn: ['lsm-tree', 'b-tree'],
    category: 'Systems',
    title: 'Write-Ahead Log (WAL)',
    summary: 'Log the intent first, apply it second — so a crash at any moment replays into a consistent state.',
    tags: ['WAL', 'durability', 'ACID', 'crash recovery', 'postgres', 'kafka'],
    module: () => import('./topics/write-ahead-log.js'),
  },
  {
    id: 'cap-theorem',
    type: 'visualization',
    buildsOn: ['raft-election', 'consistent-hashing'],
    category: 'Systems',
    title: 'CAP Theorem',
    summary: 'When the network splits, a replicated system must choose: refuse to answer, or answer possibly-stale.',
    tags: ['CAP', 'distributed systems', 'consistency', 'availability', 'PACELC', 'eventual consistency'],
    module: () => import('./topics/cap-theorem.js'),
  },
  {
    id: 'raft-election',
    type: 'visualization',
    buildsOn: ['write-ahead-log', 'consistent-hashing'],
    category: 'Systems',
    title: 'Raft Leader Election',
    summary: 'How a cluster agrees on one leader after a crash — terms, votes, and the majority that prevents split-brain.',
    tags: ['raft', 'consensus', 'etcd', 'kubernetes', 'distributed systems', 'split-brain'],
    module: () => import('./topics/raft-election.js'),
  },
  {
    id: 'raft-log-replication',
    type: 'visualization',
    buildsOn: ['raft-election', 'write-ahead-log'],
    category: 'Systems',
    title: 'Raft Log Replication',
    summary: 'How a leader copies its log to followers, and why committed entries can never be lost.',
    tags: ['raft', 'consensus', 'replication', 'commit', 'etcd', 'distributed systems'],
    module: () => import('./topics/raft-log-replication.js'),
  },
  {
    id: 'merkle-tree',
    type: 'visualization',
    buildsOn: ['hash-table', 'tree-traversals', 'cap-theorem'],
    category: 'Systems',
    title: 'Merkle Tree',
    summary: 'A tree of hashes: compare two datasets with one root check, find any difference in log n hops.',
    tags: ['merkle', 'hashing', 'git', 'blockchain', 'anti-entropy', 'replication'],
    module: () => import('./topics/merkle-tree.js'),
  },
  {
    id: 'two-phase-commit',
    type: 'visualization',
    buildsOn: ['write-ahead-log', 'raft-log-replication', 'cap-theorem'],
    category: 'Systems',
    title: 'Two-Phase Commit (2PC)',
    summary: 'Atomic transactions across machines: prepare, vote, commit — and the blocking flaw that motivated consensus.',
    tags: ['2PC', 'distributed transactions', 'XA', 'sagas', 'spanner', 'atomicity'],
    module: () => import('./topics/two-phase-commit.js'),
  },
  {
    id: 'saga-pattern',
    type: 'visualization',
    buildsOn: ['two-phase-commit', 'write-ahead-log', 'cap-theorem'],
    category: 'Systems',
    title: 'Saga Pattern',
    summary: 'A chain of local transactions plus compensating undos — distributed consistency without holding locks.',
    tags: ['saga', 'microservices', 'compensating transactions', 'eventual consistency', 'orchestration'],
    module: () => import('./topics/saga-pattern.js'),
  },
  {
    id: 'gossip-protocol',
    type: 'visualization',
    buildsOn: ['consistent-hashing', 'graph-bfs', 'merkle-tree'],
    category: 'Systems',
    title: 'Gossip Protocol',
    summary: 'Each round, every informed node tells two peers — the whole cluster knows in O(log n) rounds.',
    tags: ['gossip', 'epidemic', 'cassandra', 'membership', 'decentralized'],
    module: () => import('./topics/gossip-protocol.js'),
  },
  {
    id: 'database-indexing',
    type: 'visualization',
    buildsOn: ['b-tree', 'binary-search', 'hash-table'],
    category: 'Systems',
    title: 'Database Indexing',
    summary: 'Full scan vs index lookup vs covering index — the same query at three wildly different costs.',
    tags: ['index', 'SQL', 'EXPLAIN', 'covering index', 'postgres', 'query performance'],
    module: () => import('./topics/database-indexing.js'),
  },
  {
    id: 'git-internals',
    type: 'visualization',
    buildsOn: ['merkle-tree', 'hash-table', 'graph-bfs'],
    category: 'Systems',
    title: 'Git Internals',
    summary: 'Blobs, trees, commits — git as a content-addressed Merkle DAG, where snapshots cost like diffs.',
    tags: ['git', 'content addressing', 'merkle DAG', 'version control', 'blobs'],
    module: () => import('./topics/git-internals.js'),
  },
  {
    id: 'distributed-tracing',
    type: 'visualization',
    buildsOn: ['message-queue', 'load-balancer', 'recursion'],
    category: 'Systems',
    title: 'Distributed Tracing',
    summary: 'One trace ID, one tree of spans across six services — and the slow hop has nowhere to hide.',
    tags: ['observability', 'opentelemetry', 'jaeger', 'spans', 'microservices', 'debugging'],
    module: () => import('./topics/distributed-tracing.js'),
  },
  {
    id: 'url-shortener',
    type: 'visualization',
    buildsOn: ['hash-table', 'lru-cache', 'database-indexing', 'message-queue'],
    category: 'Systems',
    title: 'Design a URL Shortener',
    summary: 'From long URL to tiny.url/wDZ and back in milliseconds — the interview classic, fully assembled.',
    tags: ['system design', 'interview', 'base62', 'bitly', 'composition'],
    module: () => import('./topics/url-shortener.js'),
  },
  {
    id: 'message-queue',
    type: 'visualization',
    buildsOn: ['queue', 'write-ahead-log', 'saga-pattern'],
    category: 'Systems',
    title: 'Message Queues',
    summary: 'Producers rush, consumers plod, the queue absorbs the difference — plus the at-least-once catch.',
    tags: ['kafka', 'rabbitmq', 'SQS', 'at-least-once', 'backpressure', 'decoupling'],
    module: () => import('./topics/message-queue.js'),
  },
  {
    id: 'tcp-congestion',
    type: 'visualization',
    buildsOn: ['sliding-window', 'dns-resolution'],
    category: 'Systems',
    title: 'TCP: Handshake & Congestion Control',
    summary: 'SYN, SYN-ACK, ACK — then the sawtooth: probe gently upward, back off hard, forever.',
    tags: ['TCP', 'networking', 'AIMD', 'slow start', 'CUBIC', 'BBR'],
    module: () => import('./topics/tcp-congestion.js'),
  },
  {
    id: 'dns-resolution',
    type: 'visualization',
    buildsOn: ['trie', 'lru-cache', 'cdn-request-flow'],
    category: 'Systems',
    title: 'How DNS Works',
    summary: 'Root → TLD → authoritative: the hierarchical lookup behind every URL, and the caches that skip it.',
    tags: ['DNS', 'resolver', 'TTL', 'root servers', 'networking', 'anycast'],
    module: () => import('./topics/dns-resolution.js'),
  },
  {
    id: 'browser-rendering',
    type: 'visualization',
    buildsOn: ['tree-traversals', 'dns-resolution', 'tcp-congestion'],
    category: 'Systems',
    title: 'How a Browser Paints a Page',
    summary: 'HTML in, pixels out: the parse-style-layout-paint-composite pipeline, and the JS loop that breaks it.',
    tags: ['browser', 'rendering', 'DOM', 'CSSOM', 'layout', 'reflow', 'compositing', 'frontend performance'],
    module: () => import('./topics/browser-rendering.js'),
  },
  {
    id: 'event-loop',
    type: 'visualization',
    buildsOn: ['stack', 'queue', 'browser-rendering'],
    category: 'Systems',
    title: 'The Event Loop',
    summary: `One thread, two queues, strict etiquette: why setTimeout(0) isn't 0 and promises jump the line.`,
    tags: ['event loop', 'microtask', 'macrotask', 'promises', 'setTimeout', 'async', 'JavaScript runtime'],
    module: () => import('./topics/event-loop.js'),
  },
  {
    id: 'virtual-dom',
    type: 'visualization',
    buildsOn: ['browser-rendering', 'event-loop', 'edit-distance'],
    category: 'Systems',
    title: 'Virtual DOM Reconciliation',
    summary: 'Re-render in cheap JS, diff two trees, patch the real DOM minimally — and why list keys are not optional.',
    tags: ['virtual DOM', 'reconciliation', 'React', 'diffing', 'keys', 'frontend', 'tree diff'],
    module: () => import('./topics/virtual-dom.js'),
  },
  {
    id: 'web-workers',
    type: 'visualization',
    buildsOn: ['event-loop', 'browser-rendering', 'message-queue'],
    category: 'Systems',
    title: 'Web Workers: A Second Thread',
    summary: `The event loop's escape hatch: a second thread for heavy work — and the postMessage postage you pay to use it.`,
    tags: ['web workers', 'threads', 'postMessage', 'structured clone', 'transferable', 'SharedArrayBuffer', 'performance'],
    module: () => import('./topics/web-workers.js'),
  },
  {
    id: 'service-workers',
    type: 'visualization',
    buildsOn: ['web-workers', 'cdn-request-flow', 'lru-cache'],
    category: 'Systems',
    title: 'Service Workers & Offline-First',
    summary: 'A programmable proxy between page and network: intercept every request, answer from cache, survive airplane mode.',
    tags: ['service worker', 'offline', 'PWA', 'cache', 'proxy', 'stale-while-revalidate', 'fetch'],
    module: () => import('./topics/service-workers.js'),
  },
  {
    id: 'cache-invalidation',
    type: 'visualization',
    buildsOn: ['service-workers', 'cdn-request-flow', 'lru-cache', 'git-internals'],
    category: 'Systems',
    title: 'Cache Invalidation & Versioning',
    summary: 'Stale copies, thundering herds, and the naming trick that dissolves one of the two hard problems.',
    tags: ['cache invalidation', 'TTL', 'thundering herd', 'ETag', 'versioning', 'immutable', 'purge'],
    module: () => import('./topics/cache-invalidation.js'),
  },
  {
    id: 'write-caching',
    type: 'visualization',
    buildsOn: ['cache-invalidation', 'lru-cache', 'write-ahead-log'],
    category: 'Systems',
    title: 'Write-Through vs Write-Back',
    summary: 'When a write hits the cache: pay the disk now (through), promise and batch (back), or skip the cache (around).',
    tags: ['write-through', 'write-back', 'write-around', 'dirty pages', 'fsync', 'durability', 'caching'],
    module: () => import('./topics/write-caching.js'),
  },
  {
    id: 'isolation-levels',
    type: 'visualization',
    buildsOn: ['write-ahead-log', 'two-phase-commit', 'write-caching'],
    category: 'Systems',
    title: 'Transaction Isolation Levels',
    summary: 'Dirty reads, phantoms, and write skew: what concurrent transactions may see of each other, level by level.',
    tags: ['transactions', 'isolation levels', 'MVCC', 'dirty read', 'phantom read', 'write skew', 'serializable', 'databases'],
    module: () => import('./topics/isolation-levels.js'),
  },
  {
    id: 'mvcc-vacuum',
    type: 'visualization',
    buildsOn: ['isolation-levels', 'git-internals', 'lsm-tree'],
    category: 'Systems',
    title: 'MVCC Internals & VACUUM',
    summary: 'Updates that never overwrite: version chains, xmin/xmax visibility, dead tuples, and the long transaction that blocks the janitor.',
    tags: ['MVCC', 'VACUUM', 'PostgreSQL', 'dead tuples', 'bloat', 'xmin', 'versions', 'databases'],
    module: () => import('./topics/mvcc-vacuum.js'),
  },
  {
    id: 'hot-rows',
    type: 'visualization',
    buildsOn: ['mvcc-vacuum', 'message-queue', 'write-caching'],
    category: 'Systems',
    title: 'Hot Rows & Append-and-Aggregate',
    summary: 'A viral counter at 1,000 writes/sec melts a single row — four designs, from sharded counters to append-and-aggregate.',
    tags: ['hot rows', 'contention', 'sharded counters', 'append-only', 'event sourcing', 'scalability'],
    module: () => import('./topics/hot-rows.js'),
  },
  {
    id: 'cdn-request-flow',
    type: 'visualization',
    buildsOn: ['lru-cache', 'load-balancer', 'consistent-hashing', 'rate-limiter'],
    category: 'Systems',
    title: 'CDN Request Flow',
    summary: 'Follow one HTTP request through DNS, an edge cache, a load balancer, and the origin.',
    tags: ['CDN', 'caching', 'edge', 'DNS', 'cloudflare', 'composition'],
    module: () => import('./topics/cdn-request-flow.js'),
  },
  {
    id: 'rate-limiter',
    type: 'visualization',
    buildsOn: ['stack', 'hash-table'],
    category: 'Systems',
    title: 'Rate Limiter (Token Bucket)',
    summary: 'Tokens drip into a bucket; requests spend them — bursts allowed, averages enforced.',
    tags: ['rate limiting', '429', 'token bucket', 'API', 'systems design'],
    module: () => import('./topics/rate-limiter.js'),
  },
  {
    id: 'bloom-filter',
    type: 'visualization',
    buildsOn: ['hash-table'],
    category: 'Systems',
    title: 'Bloom Filter',
    summary: 'A probabilistic set in a handful of bits: "definitely not seen" or "probably seen".',
    tags: ['probabilistic', 'hashing', 'false positive', 'cassandra', 'systems design'],
    module: () => import('./topics/bloom-filter.js'),
  },
  {
    id: 'embeddings-similarity',
    type: 'visualization',
    buildsOn: ['k-means'],
    category: 'AI & ML',
    title: 'Embeddings & Similarity',
    summary: 'Meaning as geometry: similar words sit close together, and search becomes "find my neighbors".',
    tags: ['embeddings', 'vector database', 'RAG', 'semantic search', 'cosine similarity'],
    module: () => import('./topics/embeddings-similarity.js'),
  },
  {
    id: 'tsne-umap',
    type: 'visualization',
    buildsOn: ['embeddings-similarity', 'k-means', 'hnsw-search'],
    category: 'AI & ML',
    title: 't-SNE & UMAP: Seeing Embeddings',
    summary: 'Squash 768 dimensions into 2 by preserving neighborhoods — then learn which parts of the picture are lies.',
    tags: ['t-SNE', 'UMAP', 'dimensionality reduction', 'embeddings', 'visualization', 'perplexity'],
    module: () => import('./topics/tsne-umap.js'),
  },
  {
    id: 'pca',
    type: 'visualization',
    buildsOn: ['tsne-umap', 'embeddings-similarity', 'gradient-descent'],
    category: 'AI & ML',
    title: 'PCA: Principal Component Analysis',
    summary: 'Find the axes the data actually varies along — computed live — and keep only the loud ones.',
    tags: ['PCA', 'dimensionality reduction', 'eigenvectors', 'covariance', 'explained variance', 'compression'],
    module: () => import('./topics/pca.js'),
  },
  {
    id: 'activation-functions',
    type: 'visualization',
    buildsOn: ['gradient-descent'],
    category: 'AI & ML',
    title: 'Activation Functions',
    summary: 'Sigmoid, tanh, and ReLU compared — and why networks need nonlinearity at all.',
    tags: ['relu', 'sigmoid', 'tanh', 'nonlinearity', 'vanishing gradients', 'neural networks'],
    module: () => import('./topics/activation-functions.js'),
  },
  {
    id: 'gradient-descent',
    type: 'visualization',
    buildsOn: ['big-o-growth'],
    category: 'AI & ML',
    title: 'Gradient Descent',
    summary: 'Follow the slope downhill to minimize loss — the algorithm that trains every neural network.',
    tags: ['training', 'optimization', 'learning rate', 'neural networks', 'loss'],
    module: () => import('./topics/gradient-descent.js'),
  },
  {
    id: 'k-means',
    type: 'visualization',
    category: 'AI & ML',
    title: 'K-Means Clustering',
    summary: 'Group unlabeled points by repeating two moves: assign to nearest centroid, recenter the centroid.',
    tags: ['clustering', 'unsupervised learning', 'centroids'],
    module: () => import('./topics/k-means.js'),
  },
  {
    id: 'tokenization-bpe',
    type: 'visualization',
    category: 'AI & ML',
    title: 'Tokenization (BPE)',
    summary: 'Watch byte-pair encoding merge characters into the tokens LLMs actually read.',
    tags: ['tokens', 'BPE', 'LLM', 'vocabulary', 'strawberry'],
    module: () => import('./topics/tokenization-bpe.js'),
  },
  {
    id: 'softmax-temperature',
    type: 'visualization',
    category: 'AI & ML',
    title: 'Softmax & Temperature',
    summary: 'How raw model scores become probabilities — and how temperature reshapes them from greedy to creative.',
    tags: ['softmax', 'temperature', 'sampling', 'logits', 'LLM'],
    module: () => import('./topics/softmax-temperature.js'),
  },
  {
    id: 'beam-search',
    type: 'visualization',
    buildsOn: ['softmax-temperature'],
    category: 'AI & ML',
    title: 'Beam Search vs Greedy',
    summary: 'Keep k candidate sentences alive instead of one — and watch greedy decoding lose.',
    tags: ['decoding', 'beam search', 'greedy', 'LLM', 'generation'],
    module: () => import('./topics/beam-search.js'),
  },
  {
    id: 'nn-forward-pass',
    type: 'visualization',
    buildsOn: ['activation-functions', 'gradient-descent'],
    category: 'AI & ML',
    title: 'Neural Network Forward Pass',
    summary: 'Watch two inputs flow through a tiny 2-3-1 network: weights, biases, ReLU, prediction.',
    tags: ['neural network', 'forward pass', 'weights', 'MLP', 'deep learning'],
    module: () => import('./topics/nn-forward-pass.js'),
  },
  {
    id: 'convolution',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'backpropagation'],
    category: 'AI & ML',
    title: 'Convolution',
    summary: 'Slide a 3×3 kernel across an image — the same nine weights detect a pattern everywhere at once.',
    tags: ['CNN', 'kernel', 'computer vision', 'feature map', 'AlexNet', 'edge detection'],
    module: () => import('./topics/convolution.js'),
  },
  {
    id: 'kv-cache',
    type: 'visualization',
    buildsOn: ['attention', 'lru-cache'],
    category: 'AI & ML',
    title: 'KV Cache',
    summary: 'Why LLMs pause before the first token and then stream: cached Keys and Values are never recomputed.',
    tags: ['inference', 'LLM', 'vLLM', 'prefill', 'decode', 'GPU memory'],
    module: () => import('./topics/kv-cache.js'),
  },
  {
    id: 'backpropagation',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'gradient-descent'],
    category: 'AI & ML',
    title: 'Backpropagation',
    summary: 'Run the error backward through the network, blame every weight, nudge them all — loss drops.',
    tags: ['backprop', 'chain rule', 'training', 'gradients', 'deep learning'],
    module: () => import('./topics/backpropagation.js'),
  },
  {
    id: 'speculative-decoding',
    type: 'visualization',
    buildsOn: ['kv-cache', 'knowledge-distillation'],
    category: 'AI & ML',
    title: 'Speculative Decoding',
    summary: 'A small draft model guesses ahead; the big model verifies in one pass — identical output, much faster.',
    tags: ['inference', 'speculative', 'draft model', 'LLM speed', 'lossless'],
    module: () => import('./topics/speculative-decoding.js'),
  },
  {
    id: 'mixture-of-experts',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'softmax-temperature', 'load-balancer'],
    category: 'AI & ML',
    title: 'Mixture of Experts (MoE)',
    summary: 'A router picks top-k experts per token — trillion-parameter capacity at small-model compute.',
    tags: ['MoE', 'mixtral', 'sparse', 'router', 'conditional computation', 'scaling'],
    module: () => import('./topics/mixture-of-experts.js'),
  },
  {
    id: 'lora',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'quantization', 'backpropagation'],
    category: 'AI & ML',
    title: 'LoRA Fine-Tuning',
    summary: 'Freeze the giant weight matrix; train a skinny A·B correction on top — 1% of the parameters, most of the effect.',
    tags: ['LoRA', 'fine-tuning', 'QLoRA', 'adapters', 'low-rank', 'PEFT'],
    module: () => import('./topics/lora.js'),
  },
  {
    id: 'knowledge-distillation',
    type: 'visualization',
    buildsOn: ['softmax-temperature', 'nn-forward-pass', 'quantization'],
    category: 'AI & ML',
    title: 'Knowledge Distillation',
    summary: 'A big teacher model trains a small student with soft probabilities — dark knowledge included.',
    tags: ['distillation', 'compression', 'teacher student', 'DistilBERT', 'small models'],
    module: () => import('./topics/knowledge-distillation.js'),
  },
  {
    id: 'dropout',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'backpropagation', 'random-forest'],
    category: 'AI & ML',
    title: 'Dropout',
    summary: 'Randomly silence neurons during training — an ensemble of sub-networks sharing one set of weights.',
    tags: ['regularization', 'overfitting', 'dropout', 'ensemble', 'training'],
    module: () => import('./topics/dropout.js'),
  },
  {
    id: 'rag-pipeline',
    type: 'visualization',
    buildsOn: ['embeddings-similarity', 'attention', 'kv-cache'],
    category: 'AI & ML',
    title: 'RAG Pipeline',
    summary: 'The full retrieval-augmented loop: embed the question, find nearby documents, ground the answer.',
    tags: ['RAG', 'retrieval', 'vector database', 'hallucination', 'grounding', 'LLM'],
    module: () => import('./topics/rag-pipeline.js'),
  },
  {
    id: 'quantization',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'kv-cache'],
    category: 'AI & ML',
    title: 'Quantization',
    summary: 'Squeeze float weights into 8, 4, or 2 bits — watch what survives and what gets lobotomized.',
    tags: ['quantization', 'int4', 'llama.cpp', 'GPTQ', 'compression', 'inference'],
    module: () => import('./topics/quantization.js'),
  },
  {
    id: 'hnsw-search',
    type: 'visualization',
    buildsOn: ['embeddings-similarity', 'graph-bfs', 'skip-list'],
    category: 'AI & ML',
    title: 'HNSW (Vector Search at Scale)',
    summary: 'Greedy-hop a sparse highway layer, then finish in the dense layer — nearest neighbor without a full scan.',
    tags: ['vector database', 'ANN', 'HNSW', 'similarity search', 'pinecone', 'FAISS'],
    module: () => import('./topics/hnsw-search.js'),
  },
  {
    id: 'pagerank',
    type: 'visualization',
    buildsOn: ['graph-bfs', 'k-means'],
    category: 'AI & ML',
    title: 'PageRank',
    summary: `Iterate "important pages are linked to by important pages" until it converges — Google's founding idea.`,
    tags: ['pagerank', 'google', 'graphs', 'eigenvector', 'random surfer', 'ranking'],
    module: () => import('./topics/pagerank.js'),
  },
  {
    id: 'precision-recall',
    type: 'visualization',
    buildsOn: ['naive-bayes', 'ab-testing'],
    category: 'AI & ML',
    title: 'Precision, Recall & the Confusion Matrix',
    summary: 'Accuracy lies on imbalanced data — meet the four cells and two ratios that tell the truth.',
    tags: ['evaluation', 'precision', 'recall', 'F1', 'confusion matrix', 'imbalanced data'],
    module: () => import('./topics/precision-recall.js'),
  },
  {
    id: 'roc-auc',
    type: 'visualization',
    buildsOn: ['precision-recall', 'thompson-sampling'],
    category: 'AI & ML',
    title: 'ROC Curves & AUC',
    summary: 'Sweep every threshold at once: the curve is the menu of trade-offs, the area is the ranking skill.',
    tags: ['evaluation', 'ROC', 'AUC', 'threshold', 'true positive rate', 'false positive rate'],
    module: () => import('./topics/roc-auc.js'),
  },
  {
    id: 'calibration-curves',
    type: 'visualization',
    buildsOn: ['roc-auc', 'softmax-temperature'],
    category: 'AI & ML',
    title: 'Calibration & Reliability Diagrams',
    summary: `Does "90% sure" mean right 90% of the time? Plot confidence against reality and find out.`,
    tags: ['calibration', 'reliability diagram', 'ECE', 'temperature scaling', 'confidence', 'evaluation'],
    module: () => import('./topics/calibration-curves.js'),
  },
  {
    id: 'logistic-regression',
    type: 'visualization',
    buildsOn: ['gradient-descent', 'nn-forward-pass', 'roc-auc'],
    category: 'AI & ML',
    title: 'Logistic Regression',
    summary: 'A weighted sum, a sigmoid squash, and a boundary that gradient descent drags into place before your eyes.',
    tags: ['logistic regression', 'sigmoid', 'classification', 'decision boundary', 'cross-entropy', 'gradient descent'],
    module: () => import('./topics/logistic-regression.js'),
  },
  {
    id: 'regularization',
    type: 'visualization',
    buildsOn: ['logistic-regression', 'gradient-descent', 'dropout'],
    category: 'AI & ML',
    title: 'Regularization: L1 & L2',
    summary: 'The leash on the weights: L2 shrinks everything smoothly, L1 deletes features outright — watch both paths.',
    tags: ['regularization', 'L1', 'L2', 'ridge', 'lasso', 'weight decay', 'overfitting', 'sparsity'],
    module: () => import('./topics/regularization.js'),
  },
  {
    id: 'cross-validation',
    type: 'visualization',
    buildsOn: ['regularization', 'ab-testing', 'imbalanced-classification'],
    category: 'AI & ML',
    title: 'Cross-Validation & Honest Evaluation',
    summary: 'Never grade your own homework: why train accuracy lies, one split gambles, and k-fold spends data honestly.',
    tags: ['cross-validation', 'k-fold', 'train/test split', 'leakage', 'overfitting', 'evaluation', 'hyperparameters'],
    module: () => import('./topics/cross-validation.js'),
  },
  {
    id: 'hyperparameter-search',
    type: 'visualization',
    buildsOn: ['cross-validation', 'thompson-sampling', 'gradient-boosting'],
    category: 'AI & ML',
    title: 'Hyperparameter Search',
    summary: 'Grid wastes its budget, random embarrassingly wins, and Bayesian search plays bandits over configurations.',
    tags: ['hyperparameters', 'grid search', 'random search', 'Bayesian optimization', 'Hyperband', 'AutoML'],
    module: () => import('./topics/hyperparameter-search.js'),
  },
  {
    id: 'learning-curves',
    type: 'visualization',
    buildsOn: ['cross-validation', 'regularization', 'uncertainty-quantification'],
    category: 'AI & ML',
    title: 'Learning Curves & Bias–Variance',
    summary: 'More data, or a better model? Plot the learning curve and the gap (or its absence) prescribes the treatment.',
    tags: ['learning curves', 'bias', 'variance', 'overfitting', 'underfitting', 'double descent', 'diagnosis'],
    module: () => import('./topics/learning-curves.js'),
  },
  {
    id: 'gradient-flow',
    type: 'visualization',
    buildsOn: ['backpropagation', 'nn-forward-pass', 'transformer-block'],
    category: 'AI & ML',
    title: 'Vanishing & Exploding Gradients',
    summary: 'Backprop multiplies a factor per layer — below 1 the signal starves, above 1 it detonates. Depth was unusable until three fixes.',
    tags: ['vanishing gradients', 'exploding gradients', 'residual connections', 'ReLU', 'normalization', 'deep learning', 'ResNet'],
    module: () => import('./topics/gradient-flow.js'),
  },
  {
    id: 'normalization',
    type: 'visualization',
    buildsOn: ['gradient-flow', 'transformer-block', 'lr-schedules'],
    category: 'AI & ML',
    title: 'BatchNorm & LayerNorm',
    summary: 'Re-standardize the signal at every layer — and the BN-vs-LN war is just an argument about which axis.',
    tags: ['batch normalization', 'layer normalization', 'RMSNorm', 'training stability', 'deep learning'],
    module: () => import('./topics/normalization.js'),
  },
  {
    id: 'loss-landscapes',
    type: 'visualization',
    buildsOn: ['gradient-descent', 'gradient-flow', 'learning-curves'],
    category: 'AI & ML',
    title: 'Loss Landscapes & Optimization Geometry',
    summary: 'The terrain under gradient descent: trapping basins, stalling saddles, and why flat minima generalize.',
    tags: ['loss landscape', 'saddle points', 'flat minima', 'non-convex', 'SGD', 'optimization', 'SAM'],
    module: () => import('./topics/loss-landscapes.js'),
  },
  {
    id: 'adam-optimizer',
    type: 'visualization',
    buildsOn: ['gradient-descent', 'loss-landscapes', 'regularization'],
    category: 'AI & ML',
    title: 'Momentum, RMSProp & Adam',
    summary: 'Three optimizers race a ravine: GD zigzags and starves, momentum remembers, Adam adapts per-coordinate.',
    tags: ['Adam', 'momentum', 'RMSProp', 'AdamW', 'optimizers', 'learning rate', 'training'],
    module: () => import('./topics/adam-optimizer.js'),
  },
  {
    id: 'lr-schedules',
    type: 'visualization',
    buildsOn: ['adam-optimizer', 'loss-landscapes', 'hyperparameter-search'],
    category: 'AI & ML',
    title: 'Learning-Rate Schedules & Warmup',
    summary: 'Big steps to cover ground, small steps to settle — schedules turn one impossible constant into a dial over time.',
    tags: ['learning rate', 'warmup', 'cosine annealing', 'step decay', 'LR range test', 'schedules', 'training'],
    module: () => import('./topics/lr-schedules.js'),
  },
  {
    id: 'early-stopping',
    type: 'visualization',
    buildsOn: ['learning-curves', 'regularization', 'hyperparameter-search'],
    category: 'AI & ML',
    title: 'Early Stopping & Patience',
    summary: 'Validation turns while training keeps falling — quit at the turn, with a patience counter to ignore the noise.',
    tags: ['early stopping', 'patience', 'checkpoints', 'overfitting', 'regularization', 'training'],
    module: () => import('./topics/early-stopping.js'),
  },
  {
    id: 'threshold-optimization',
    type: 'visualization',
    buildsOn: ['roc-auc', 'precision-recall', 'calibration-curves'],
    category: 'AI & ML',
    title: 'Picking a Threshold with Real Costs',
    summary: 'Attach a price to each mistake and the threshold debate becomes arithmetic — watch the optimum slide when costs flip.',
    tags: ['threshold', 'cost-sensitive', 'expected cost', 'decision theory', 'operating point', 'evaluation'],
    module: () => import('./topics/threshold-optimization.js'),
  },
  {
    id: 'imbalanced-classification',
    type: 'visualization',
    buildsOn: ['precision-recall', 'threshold-optimization', 'roc-auc'],
    category: 'AI & ML',
    title: 'Imbalanced Data: When 99% Is One Class',
    summary: 'Fraud is 1% of the data: watch accuracy lie, ROC flatter, and the fixes that make models care about the rare class.',
    tags: ['imbalanced data', 'class weights', 'oversampling', 'SMOTE', 'undersampling', 'fraud', 'rare events'],
    module: () => import('./topics/imbalanced-classification.js'),
  },
  {
    id: 'focal-loss',
    type: 'visualization',
    buildsOn: ['imbalanced-classification', 'logistic-regression', 'entropy'],
    category: 'AI & ML',
    title: 'Focal Loss & Hard Examples',
    summary: 'Easy examples drown the gradient by sheer headcount — (1−p)^γ mutes the confident and amplifies the struggling.',
    tags: ['focal loss', 'hard examples', 'OHEM', 'RetinaNet', 'object detection', 'loss functions'],
    module: () => import('./topics/focal-loss.js'),
  },
  {
    id: 'uncertainty-quantification',
    type: 'visualization',
    buildsOn: ['dropout', 'calibration-curves'],
    category: 'AI & ML',
    title: `Uncertainty: Teaching Models to Say "I Don't Know"`,
    summary: 'Two kinds of doubt live in every prediction — and MC dropout makes a network confess which one it has.',
    tags: ['uncertainty', 'epistemic', 'aleatoric', 'MC dropout', 'ensembles', 'selective prediction', 'conformal'],
    module: () => import('./topics/uncertainty-quantification.js'),
  },
  {
    id: 'adversarial-examples',
    type: 'visualization',
    buildsOn: ['logistic-regression', 'gradient-descent', 'uncertainty-quantification'],
    category: 'AI & ML',
    title: 'Adversarial Examples & FGSM',
    summary: 'Point the gradient at the input instead of the weights: one deliberate nudge turns 97% spam into 14%.',
    tags: ['adversarial examples', 'FGSM', 'robustness', 'security', 'evasion', 'gradients'],
    module: () => import('./topics/adversarial-examples.js'),
  },
  {
    id: 'saliency-maps',
    type: 'visualization',
    buildsOn: ['adversarial-examples', 'multi-head-attention', 'logistic-regression'],
    category: 'AI & ML',
    title: 'Saliency Maps & Feature Attribution',
    summary: 'Ask the model WHY — gradients and occlusion point at the responsible features, and sanity checks catch lying explanations.',
    tags: ['saliency', 'attribution', 'interpretability', 'explainability', 'Grad-CAM', 'integrated gradients', 'XAI'],
    module: () => import('./topics/saliency-maps.js'),
  },
  {
    id: 'lime',
    type: 'visualization',
    buildsOn: ['saliency-maps', 'logistic-regression', 'cross-validation'],
    category: 'AI & ML',
    title: 'LIME: Explaining Black Boxes Locally',
    summary: 'No weights, no gradients, just an API? Sample around the input, fit a local line, read the line.',
    tags: ['LIME', 'SHAP', 'interpretability', 'black box', 'local surrogate', 'explainability', 'XAI'],
    module: () => import('./topics/lime.js'),
  },
  {
    id: 'influence-functions',
    type: 'visualization',
    buildsOn: ['lime', 'logistic-regression', 'cross-validation'],
    category: 'AI & ML',
    title: 'Influence: Which Training Data Did This?',
    summary: 'Delete one training example, retrain, watch the prediction move — exact influence, and the mislabeled point it catches.',
    tags: ['influence functions', 'data valuation', 'leave-one-out', 'mislabeled data', 'data debugging', 'TracIn'],
    module: () => import('./topics/influence-functions.js'),
  },
  {
    id: 'naive-bayes',
    type: 'visualization',
    buildsOn: ['thompson-sampling', 'tokenization-bpe', 'ab-testing'],
    category: 'AI & ML',
    title: 'Naive Bayes (Spam Filter)',
    summary: 'Watch each word shift the odds spam-ward or ham-ward — Bayes theorem reading your email.',
    tags: ['naive bayes', 'spam', 'classification', 'priors', 'laplace smoothing'],
    module: () => import('./topics/naive-bayes.js'),
  },
  {
    id: 'thompson-sampling',
    type: 'visualization',
    buildsOn: ['multi-armed-bandits', 'ab-testing'],
    category: 'AI & ML',
    title: 'Thompson Sampling',
    summary: 'Beta-distribution beliefs that sharpen with data — exploration that fades automatically as certainty grows.',
    tags: ['thompson sampling', 'bayesian', 'beta distribution', 'bandits', 'uncertainty'],
    module: () => import('./topics/thompson-sampling.js'),
  },
  {
    id: 'multi-armed-bandits',
    type: 'visualization',
    buildsOn: ['ab-testing', 'value-iteration'],
    category: 'AI & ML',
    title: 'Multi-Armed Bandits',
    summary: 'Explore a little, exploit a lot — adaptive experiments that stop wasting traffic on losers.',
    tags: ['bandits', 'epsilon-greedy', 'explore exploit', 'UCB', 'thompson sampling'],
    module: () => import('./topics/multi-armed-bandits.js'),
  },
  {
    id: 'value-iteration',
    type: 'visualization',
    buildsOn: ['gradient-descent', 'pagerank', 'memoization'],
    category: 'AI & ML',
    title: 'Value Iteration (Reinforcement Learning)',
    summary: 'Watch value flow backward from the goal until the best route to act simply falls out of the numbers.',
    tags: ['reinforcement learning', 'bellman', 'Q-learning', 'grid world', 'DQN', 'policy'],
    module: () => import('./topics/value-iteration.js'),
  },
  {
    id: 'random-forest',
    type: 'visualization',
    buildsOn: ['binary-search-tree'],
    category: 'AI & ML',
    title: 'Random Forest',
    summary: 'Three different decision trees classify the same animal — then vote. Ensembles beat soloists.',
    tags: ['decision trees', 'ensemble', 'bagging', 'machine learning', 'tabular'],
    module: () => import('./topics/random-forest.js'),
  },
  {
    id: 'gradient-boosting',
    type: 'visualization',
    buildsOn: ['random-forest', 'gradient-descent', 'learning-curves'],
    category: 'AI & ML',
    title: 'Gradient Boosting',
    summary: `Each tree fits the previous ensemble's mistakes — gradient descent in function space, and the king of tabular data.`,
    tags: ['gradient boosting', 'XGBoost', 'LightGBM', 'ensembles', 'residuals', 'stumps', 'tabular data'],
    module: () => import('./topics/gradient-boosting.js'),
  },
  {
    id: 'transformer-block',
    type: 'visualization',
    buildsOn: ['attention', 'nn-forward-pass', 'tokenization-bpe', 'softmax-temperature'],
    category: 'AI & ML',
    title: 'The Transformer Block',
    summary: 'The full assembly: attention, residuals, layer norm, and the FFN — one complete block of a GPT.',
    tags: ['transformer', 'GPT', 'residual', 'layer norm', 'architecture', 'capstone'],
    module: () => import('./topics/transformer-block.js'),
  },
  {
    id: 'rope',
    type: 'visualization',
    buildsOn: ['positional-encoding', 'attention', 'kv-cache'],
    category: 'AI & ML',
    title: 'RoPE (Rotary Embeddings)',
    summary: 'Encode position as rotation — relative distance falls out of every attention dot product for free.',
    tags: ['RoPE', 'rotary', 'llama', 'long context', 'YaRN', 'position'],
    module: () => import('./topics/rope.js'),
  },
  {
    id: 'positional-encoding',
    type: 'visualization',
    buildsOn: ['attention', 'transformer-block'],
    category: 'AI & ML',
    title: 'Positional Encoding',
    summary: 'Sinusoidal fingerprints for word order — how attention learns that position exists at all.',
    tags: ['positional encoding', 'RoPE', 'sinusoidal', 'transformers', 'context length'],
    module: () => import('./topics/positional-encoding.js'),
  },
  {
    id: 'multi-head-attention',
    type: 'visualization',
    buildsOn: ['attention', 'transformer-block'],
    category: 'AI & ML',
    title: 'Multi-Head Attention',
    summary: 'Two heads, two different attention patterns, one concatenated answer — parallel relationship detectors.',
    tags: ['multi-head', 'attention', 'transformers', 'induction heads', 'interpretability'],
    module: () => import('./topics/multi-head-attention.js'),
  },
  {
    id: 'attention',
    type: 'visualization',
    buildsOn: ['tokenization-bpe', 'softmax-temperature', 'embeddings-similarity'],
    category: 'AI & ML',
    title: 'Attention Mechanism',
    summary: 'The heart of the Transformer: queries, keys, values, and the softmax heatmap that lets tokens look at each other.',
    tags: ['transformers', 'self-attention', 'softmax', 'QKV', 'LLM'],
    searchText: 'attention is all you need scaled dot product query key value neural network deep learning',
    module: () => import('./topics/attention.js'),
  },
];

// Ranked search over everything in the registry. Title matches beat tag
// matches beat summary matches; words within one typo of a title word or
// tag still count (so "binary serch" finds Binary Search).
function withinOneEdit(a, b) {
  if (a === b) return true;
  if (Math.abs(a.length - b.length) > 1) return false;
  let i = 0;
  let j = 0;
  let edits = 0;
  while (i < a.length && j < b.length) {
    if (a[i] === b[j]) { i += 1; j += 1; continue; }
    edits += 1;
    if (edits > 1) return false;
    if (a.length > b.length) i += 1;
    else if (b.length > a.length) j += 1;
    else { i += 1; j += 1; }
  }
  return edits + (a.length - i) + (b.length - j) <= 1;
}

export function searchTopics(rawQuery) {
  const query = String(rawQuery ?? '').trim().toLowerCase();
  if (!query) return [];
  const words = query.split(/\s+/);
  const scored = [];
  for (const entry of topics) {
    const title = entry.title.toLowerCase();
    const titleWords = title.split(/[^a-z0-9]+/).filter(Boolean);
    const tags = (entry.tags ?? []).map((t) => t.toLowerCase());
    const rest = `${entry.summary} ${entry.category} ${entry.searchText ?? ''}`.toLowerCase();
    let total = 0;
    let allMatched = true;
    for (const word of words) {
      let score = 0;
      if (title.startsWith(word)) score = 100;
      else if (titleWords.some((w) => w.startsWith(word))) score = 70;
      else if (title.includes(word)) score = 55;
      else if (tags.some((t) => t.includes(word))) score = 40;
      else if (word.length >= 5 && (titleWords.some((w) => withinOneEdit(w, word)) || tags.some((t) => withinOneEdit(t, word)))) score = 30;
      else if (rest.includes(word)) score = 15;
      if (score === 0) { allMatched = false; break; }
      total += score;
    }
    if (allMatched) scored.push({ entry, score: total });
  }
  return scored
    .sort((a, b) => b.score - a.score || a.entry.title.length - b.entry.title.length)
    .map((x) => x.entry);
}

// Inline cross-linking: split text into segments, turning the first mention
// of any other topic's exact title into a link segment. Longest title wins
// at a position; matches must be word-bounded; one link per topic per text.
const isWordChar = (ch) => /[A-Za-z0-9]/.test(ch ?? '');

export function linkifyByTitle(text, excludeId = null) {
  const candidates = topics
    .filter((t) => t.type === 'visualization' && t.id !== excludeId)
    .sort((a, b) => b.title.length - a.title.length);
  const segments = [];
  const linked = new Set();
  let rest = String(text ?? '');
  while (rest.length > 0) {
    let best = null;
    for (const entry of candidates) {
      if (linked.has(entry.id)) continue;
      let from = 0;
      while (from <= rest.length - entry.title.length) {
        const idx = rest.indexOf(entry.title, from);
        if (idx === -1) break;
        const bounded = !isWordChar(rest[idx - 1]) && !isWordChar(rest[idx + entry.title.length]);
        if (bounded) {
          if (!best || idx < best.idx) best = { id: entry.id, title: entry.title, idx };
          break;
        }
        from = idx + 1;
      }
    }
    if (!best) {
      segments.push({ text: rest });
      break;
    }
    if (best.idx > 0) segments.push({ text: rest.slice(0, best.idx) });
    segments.push({ text: best.title, id: best.id });
    linked.add(best.id);
    rest = rest.slice(best.idx + best.title.length);
  }
  return segments;
}
