// The single source of truth for everything on the site.
// Adding content = one entry here + one module in src/topics/ (or one HTML
// file in articles/ for type 'article'). Homepage search indexes title,
// summary, category, tags, and searchText.

export const categories = [
  'Data Structures',
  'Sorting',
  'Searching',
  'Concepts',
  'Systems',
  'AI & ML',
  'Papers',
];

// Entries may declare `buildsOn: [ids]` — the simpler ideas they are made of.
// Topic pages render these as "Built from" links, and compute the reverse
// ("Next up") automatically, so complex topics always point back to their
// ingredients and simple topics advertise what they unlock.

export const topics = [
  {
    id: 'linked-list',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Linked List',
    summary: 'A chain of nodes connected by pointers — append, search, and remove by re-linking.',
    tags: ['pointers', 'nodes', 'traversal'],
    module: () => import('./topics/linked-list.js'),
  },
  {
    id: 'stack',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Stack',
    summary: 'Last In, First Out: push and pop from the top, the way undo history works.',
    tags: ['LIFO', 'push', 'pop'],
    module: () => import('./topics/stack.js'),
  },
  {
    id: 'queue',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Queue',
    summary: 'First In, First Out: enqueue at the back, dequeue from the front, like a line at a store.',
    tags: ['FIFO', 'enqueue', 'dequeue'],
    module: () => import('./topics/queue.js'),
  },
  {
    id: 'hash-table',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Hash Table',
    summary: 'Turn a key into a bucket index, handle collisions with probing, rehash as it fills.',
    tags: ['hashing', 'collisions', 'linear probing', 'load factor', 'rehash'],
    module: () => import('./topics/hash-table.js'),
  },
  {
    id: 'binary-search-tree',
    type: 'visualization',
    buildsOn: ['binary-search'],
    category: 'Data Structures',
    title: 'Binary Search Tree',
    summary: 'Smaller values go left, larger go right — so lookups skip half the tree at every node.',
    tags: ['BST', 'tree', 'insert', 'search'],
    module: () => import('./topics/binary-search-tree.js'),
  },
  {
    id: 'insertion-sort',
    type: 'visualization',
    category: 'Sorting',
    title: 'Insertion Sort',
    summary: 'Slide each value left into its place in a growing sorted prefix, like sorting cards in your hand.',
    tags: ['sorting', 'nearly sorted', 'O(n^2)', 'adaptive'],
    module: () => import('./topics/insertion-sort.js'),
  },
  {
    id: 'selection-sort',
    type: 'visualization',
    category: 'Sorting',
    title: 'Selection Sort',
    summary: 'Scan for the smallest remaining value and swap it into place — minimum swaps, maximum scanning.',
    tags: ['sorting', 'minimum', 'O(n^2)'],
    module: () => import('./topics/selection-sort.js'),
  },
  {
    id: 'tree-traversals',
    type: 'visualization',
    buildsOn: ['binary-search-tree', 'recursion', 'queue'],
    category: 'Data Structures',
    title: 'Tree Traversals',
    summary: 'In-order, pre-order, post-order, and level-order — four ways to walk a tree, each with a job.',
    tags: ['BFS', 'DFS', 'in-order', 'level-order', 'tree'],
    module: () => import('./topics/tree-traversals.js'),
  },
  {
    id: 'binary-heap',
    type: 'visualization',
    buildsOn: ['binary-search-tree'],
    category: 'Data Structures',
    title: 'Binary Heap (Priority Queue)',
    summary: 'A tree where every parent beats its children — the maximum is always one peek away.',
    tags: ['priority queue', 'heap', 'bubble up', 'sift down'],
    module: () => import('./topics/binary-heap.js'),
  },
  {
    id: 'b-tree',
    type: 'visualization',
    buildsOn: ['binary-search-tree', 'binary-search'],
    category: 'Data Structures',
    title: 'B-Trees (How Databases Read)',
    summary: 'Nodes hold multiple keys and split upward as they fill — the index behind Postgres and MySQL.',
    tags: ['b-tree', 'database index', 'postgres', 'mysql', 'disk', 'balanced'],
    module: () => import('./topics/b-tree.js'),
  },
  {
    id: 'trie',
    type: 'visualization',
    buildsOn: ['hash-table', 'tree-traversals'],
    category: 'Data Structures',
    title: 'Trie (Prefix Tree)',
    summary: 'Words stored letter by letter, prefixes shared — autocomplete is just a subtree walk.',
    tags: ['trie', 'autocomplete', 'prefix', 'search suggestions', 'IP routing'],
    module: () => import('./topics/trie.js'),
  },
  {
    id: 'topological-sort',
    type: 'visualization',
    buildsOn: ['graph-bfs', 'queue'],
    category: 'Data Structures',
    title: 'Topological Sort',
    summary: 'Order tasks so every prerequisite comes first — and detect circular dependencies for free.',
    tags: ['DAG', 'kahn', 'build order', 'dependencies', 'npm', 'airflow'],
    module: () => import('./topics/topological-sort.js'),
  },
  {
    id: 'union-find',
    type: 'visualization',
    buildsOn: ['tree-traversals'],
    category: 'Data Structures',
    title: 'Union-Find (Disjoint Sets)',
    summary: 'Merge groups and test connectivity in near-constant time — parent pointers plus two sly tricks.',
    tags: ['disjoint sets', 'kruskal', 'connectivity', 'path compression', 'inverse ackermann'],
    module: () => import('./topics/union-find.js'),
  },
  {
    id: 'skip-list',
    type: 'visualization',
    buildsOn: ['linked-list', 'binary-search'],
    category: 'Data Structures',
    title: 'Skip List',
    summary: 'A linked list with probabilistic express lanes — O(log n) search without any rebalancing.',
    tags: ['skip list', 'redis', 'probabilistic', 'sorted set', 'express lanes'],
    module: () => import('./topics/skip-list.js'),
  },
  {
    id: 'graph-bfs',
    type: 'visualization',
    buildsOn: ['queue', 'tree-traversals'],
    category: 'Data Structures',
    title: 'Graph BFS',
    summary: 'Explore a graph in expanding rings with a queue — the fewest-hops path falls out for free.',
    tags: ['graph', 'breadth-first', 'shortest path', 'network'],
    module: () => import('./topics/graph-bfs.js'),
  },
  {
    id: 'dijkstra',
    type: 'visualization',
    buildsOn: ['graph-bfs', 'binary-heap'],
    category: 'Data Structures',
    title: "Dijkstra's Shortest Path",
    summary: 'Find the cheapest route in a weighted graph by always expanding the cheapest known node.',
    tags: ['graph', 'shortest path', 'GPS', 'greedy', 'weighted'],
    module: () => import('./topics/dijkstra.js'),
  },
  {
    id: 'a-star',
    type: 'visualization',
    buildsOn: ['dijkstra'],
    category: 'Data Structures',
    title: 'A* Search',
    summary: 'Shortest path with a compass: expand by g + h, and skip everything pointing away from the goal.',
    tags: ['pathfinding', 'heuristic', 'games', 'GPS', 'graph'],
    module: () => import('./topics/a-star.js'),
  },
  {
    id: 'bubble-sort',
    type: 'visualization',
    category: 'Sorting',
    title: 'Bubble Sort',
    summary: 'Compare neighbors and swap — the largest value bubbles to the end on every pass.',
    tags: ['sorting', 'swaps', 'O(n^2)'],
    module: () => import('./topics/bubble-sort.js'),
  },
  {
    id: 'merge-sort',
    type: 'visualization',
    buildsOn: ['recursion'],
    category: 'Sorting',
    title: 'Merge Sort',
    summary: 'Split the array in half, sort each half, then merge — divide and conquer at O(n log n).',
    tags: ['sorting', 'divide and conquer', 'stable', 'O(n log n)'],
    module: () => import('./topics/merge-sort.js'),
  },
  {
    id: 'quick-sort',
    type: 'visualization',
    buildsOn: ['recursion'],
    category: 'Sorting',
    title: 'Quick Sort',
    summary: 'Pick a pivot, partition the array around it, recurse — fast in practice and in place.',
    tags: ['sorting', 'pivot', 'partition', 'recursion'],
    module: () => import('./topics/quick-sort.js'),
  },
  {
    id: 'heap-sort',
    type: 'visualization',
    buildsOn: ['binary-heap'],
    category: 'Sorting',
    title: 'Heap Sort',
    summary: 'Build a max-heap inside the array, then repeatedly move the largest value to the end.',
    tags: ['sorting', 'heap', 'sift down', 'O(n log n)'],
    module: () => import('./topics/heap-sort.js'),
  },
  {
    id: 'linear-search',
    type: 'visualization',
    category: 'Searching',
    title: 'Linear Search',
    summary: 'Check every element from left to right — simple, and the best you can do unsorted.',
    tags: ['search', 'O(n)'],
    module: () => import('./topics/linear-search.js'),
  },
  {
    id: 'binary-search',
    type: 'visualization',
    category: 'Searching',
    title: 'Binary Search',
    summary: 'Halve the search range on every comparison — find anything in a sorted array in O(log n).',
    tags: ['search', 'sorted', 'O(log n)', 'divide and conquer'],
    module: () => import('./topics/binary-search.js'),
  },
  {
    id: 'recursion',
    type: 'visualization',
    category: 'Concepts',
    title: 'Recursion',
    summary: 'Watch a function call itself: the call tree for factorial and Fibonacci, opening and returning.',
    tags: ['call stack', 'base case', 'fibonacci', 'factorial'],
    module: () => import('./topics/recursion.js'),
  },
  {
    id: 'big-o-growth',
    type: 'visualization',
    category: 'Concepts',
    title: 'Big-O Growth Rates',
    summary: 'Watch log n, n, n log n, and n² grow apart — the chart that explains why algorithms matter.',
    tags: ['complexity', 'big-o', 'performance', 'scaling'],
    module: () => import('./topics/big-o-growth.js'),
  },
  {
    id: 'huffman-coding',
    type: 'visualization',
    buildsOn: ['binary-heap', 'trie', 'tree-traversals'],
    category: 'Concepts',
    title: 'Huffman Coding',
    summary: 'Build the optimal prefix code by always merging the two rarest symbols — compression from a greedy loop.',
    tags: ['compression', 'huffman', 'zip', 'greedy', 'prefix code', 'entropy'],
    module: () => import('./topics/huffman-coding.js'),
  },
  {
    id: 'two-pointers',
    type: 'visualization',
    buildsOn: ['binary-search'],
    category: 'Concepts',
    title: 'Two Pointers',
    summary: 'Find a pair summing to a target in one pass — squeeze from both ends of a sorted array.',
    tags: ['technique', 'pair sum', 'O(n)', 'interview'],
    module: () => import('./topics/two-pointers.js'),
  },
  {
    id: 'sliding-window',
    type: 'visualization',
    buildsOn: ['two-pointers'],
    category: 'Concepts',
    title: 'Sliding Window',
    summary: 'Find the longest run under a budget in one pass — grow the window right, shrink it left.',
    tags: ['sliding window', 'technique', 'O(n)', 'TCP', 'substring'],
    module: () => import('./topics/sliding-window.js'),
  },
  {
    id: 'memoization',
    type: 'visualization',
    buildsOn: ['recursion', 'hash-table'],
    category: 'Concepts',
    title: 'Memoization (Dynamic Programming)',
    summary: 'Cache every answer the first time you compute it — watch the exponential call tree collapse.',
    tags: ['dynamic programming', 'cache', 'fibonacci', 'optimization'],
    module: () => import('./topics/memoization.js'),
  },
  {
    id: 'lru-cache',
    type: 'visualization',
    buildsOn: ['hash-table', 'linked-list'],
    category: 'Systems',
    title: 'LRU Cache',
    summary: 'Keep the hottest items, evict the least-recently-used — hash table + linked list, fused.',
    tags: ['cache', 'eviction', 'O(1)', 'redis', 'systems design'],
    module: () => import('./topics/lru-cache.js'),
  },
  {
    id: 'load-balancer',
    type: 'visualization',
    buildsOn: ['queue', 'hash-table'],
    category: 'Systems',
    title: 'Load Balancer',
    summary: 'Route incoming requests across servers — round-robin vs least-connections, on identical traffic.',
    tags: ['systems design', 'round robin', 'scaling', 'nginx', 'distributed systems'],
    module: () => import('./topics/load-balancer.js'),
  },
  {
    id: 'consistent-hashing',
    type: 'visualization',
    buildsOn: ['hash-table'],
    category: 'Systems',
    title: 'Consistent Hashing',
    summary: 'Hash servers AND keys onto a ring — adding a server moves only its neighbors, not everything.',
    tags: ['cassandra', 'dynamodb', 'distributed systems', 'ring', 'sharding'],
    module: () => import('./topics/consistent-hashing.js'),
  },
  {
    id: 'lsm-tree',
    type: 'visualization',
    buildsOn: ['merge-sort', 'bloom-filter', 'binary-search'],
    category: 'Systems',
    title: 'LSM Trees (How Cassandra Writes)',
    summary: 'Writes land in a memtable, flush to immutable sorted files, and merge in the background.',
    tags: ['cassandra', 'rocksdb', 'database', 'storage engine', 'write path'],
    module: () => import('./topics/lsm-tree.js'),
  },
  {
    id: 'write-ahead-log',
    type: 'visualization',
    buildsOn: ['lsm-tree', 'b-tree'],
    category: 'Systems',
    title: 'Write-Ahead Log (WAL)',
    summary: 'Log the intent first, apply it second — so a crash at any moment replays into a consistent state.',
    tags: ['WAL', 'durability', 'ACID', 'crash recovery', 'postgres', 'kafka'],
    module: () => import('./topics/write-ahead-log.js'),
  },
  {
    id: 'cap-theorem',
    type: 'visualization',
    buildsOn: ['raft-election', 'consistent-hashing'],
    category: 'Systems',
    title: 'CAP Theorem',
    summary: 'When the network splits, a replicated system must choose: refuse to answer, or answer possibly-stale.',
    tags: ['CAP', 'distributed systems', 'consistency', 'availability', 'PACELC', 'eventual consistency'],
    module: () => import('./topics/cap-theorem.js'),
  },
  {
    id: 'raft-election',
    type: 'visualization',
    buildsOn: ['write-ahead-log', 'consistent-hashing'],
    category: 'Systems',
    title: 'Raft Leader Election',
    summary: 'How a cluster agrees on one leader after a crash — terms, votes, and the majority that prevents split-brain.',
    tags: ['raft', 'consensus', 'etcd', 'kubernetes', 'distributed systems', 'split-brain'],
    module: () => import('./topics/raft-election.js'),
  },
  {
    id: 'rate-limiter',
    type: 'visualization',
    buildsOn: ['stack', 'hash-table'],
    category: 'Systems',
    title: 'Rate Limiter (Token Bucket)',
    summary: 'Tokens drip into a bucket; requests spend them — bursts allowed, averages enforced.',
    tags: ['rate limiting', '429', 'token bucket', 'API', 'systems design'],
    module: () => import('./topics/rate-limiter.js'),
  },
  {
    id: 'bloom-filter',
    type: 'visualization',
    buildsOn: ['hash-table'],
    category: 'Systems',
    title: 'Bloom Filter',
    summary: 'A probabilistic set in a handful of bits: "definitely not seen" or "probably seen".',
    tags: ['probabilistic', 'hashing', 'false positive', 'cassandra', 'systems design'],
    module: () => import('./topics/bloom-filter.js'),
  },
  {
    id: 'embeddings-similarity',
    type: 'visualization',
    buildsOn: ['k-means'],
    category: 'AI & ML',
    title: 'Embeddings & Similarity',
    summary: 'Meaning as geometry: similar words sit close together, and search becomes "find my neighbors".',
    tags: ['embeddings', 'vector database', 'RAG', 'semantic search', 'cosine similarity'],
    module: () => import('./topics/embeddings-similarity.js'),
  },
  {
    id: 'activation-functions',
    type: 'visualization',
    buildsOn: ['gradient-descent'],
    category: 'AI & ML',
    title: 'Activation Functions',
    summary: 'Sigmoid, tanh, and ReLU compared — and why networks need nonlinearity at all.',
    tags: ['relu', 'sigmoid', 'tanh', 'nonlinearity', 'vanishing gradients', 'neural networks'],
    module: () => import('./topics/activation-functions.js'),
  },
  {
    id: 'gradient-descent',
    type: 'visualization',
    buildsOn: ['big-o-growth'],
    category: 'AI & ML',
    title: 'Gradient Descent',
    summary: 'Follow the slope downhill to minimize loss — the algorithm that trains every neural network.',
    tags: ['training', 'optimization', 'learning rate', 'neural networks', 'loss'],
    module: () => import('./topics/gradient-descent.js'),
  },
  {
    id: 'k-means',
    type: 'visualization',
    category: 'AI & ML',
    title: 'K-Means Clustering',
    summary: 'Group unlabeled points by repeating two moves: assign to nearest centroid, recenter the centroid.',
    tags: ['clustering', 'unsupervised learning', 'centroids'],
    module: () => import('./topics/k-means.js'),
  },
  {
    id: 'tokenization-bpe',
    type: 'visualization',
    category: 'AI & ML',
    title: 'Tokenization (BPE)',
    summary: 'Watch byte-pair encoding merge characters into the tokens LLMs actually read.',
    tags: ['tokens', 'BPE', 'LLM', 'vocabulary', 'strawberry'],
    module: () => import('./topics/tokenization-bpe.js'),
  },
  {
    id: 'softmax-temperature',
    type: 'visualization',
    category: 'AI & ML',
    title: 'Softmax & Temperature',
    summary: 'How raw model scores become probabilities — and how temperature reshapes them from greedy to creative.',
    tags: ['softmax', 'temperature', 'sampling', 'logits', 'LLM'],
    module: () => import('./topics/softmax-temperature.js'),
  },
  {
    id: 'beam-search',
    type: 'visualization',
    buildsOn: ['softmax-temperature'],
    category: 'AI & ML',
    title: 'Beam Search vs Greedy',
    summary: 'Keep k candidate sentences alive instead of one — and watch greedy decoding lose.',
    tags: ['decoding', 'beam search', 'greedy', 'LLM', 'generation'],
    module: () => import('./topics/beam-search.js'),
  },
  {
    id: 'nn-forward-pass',
    type: 'visualization',
    buildsOn: ['activation-functions', 'gradient-descent'],
    category: 'AI & ML',
    title: 'Neural Network Forward Pass',
    summary: 'Watch two inputs flow through a tiny 2-3-1 network: weights, biases, ReLU, prediction.',
    tags: ['neural network', 'forward pass', 'weights', 'MLP', 'deep learning'],
    module: () => import('./topics/nn-forward-pass.js'),
  },
  {
    id: 'convolution',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'backpropagation'],
    category: 'AI & ML',
    title: 'Convolution',
    summary: 'Slide a 3×3 kernel across an image — the same nine weights detect a pattern everywhere at once.',
    tags: ['CNN', 'kernel', 'computer vision', 'feature map', 'AlexNet', 'edge detection'],
    module: () => import('./topics/convolution.js'),
  },
  {
    id: 'kv-cache',
    type: 'visualization',
    buildsOn: ['attention', 'lru-cache'],
    category: 'AI & ML',
    title: 'KV Cache',
    summary: 'Why LLMs pause before the first token and then stream: cached Keys and Values are never recomputed.',
    tags: ['inference', 'LLM', 'vLLM', 'prefill', 'decode', 'GPU memory'],
    module: () => import('./topics/kv-cache.js'),
  },
  {
    id: 'backpropagation',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'gradient-descent'],
    category: 'AI & ML',
    title: 'Backpropagation',
    summary: 'Run the error backward through the network, blame every weight, nudge them all — loss drops.',
    tags: ['backprop', 'chain rule', 'training', 'gradients', 'deep learning'],
    module: () => import('./topics/backpropagation.js'),
  },
  {
    id: 'lora',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'quantization', 'backpropagation'],
    category: 'AI & ML',
    title: 'LoRA Fine-Tuning',
    summary: 'Freeze the giant weight matrix; train a skinny A·B correction on top — 1% of the parameters, most of the effect.',
    tags: ['LoRA', 'fine-tuning', 'QLoRA', 'adapters', 'low-rank', 'PEFT'],
    module: () => import('./topics/lora.js'),
  },
  {
    id: 'knowledge-distillation',
    type: 'visualization',
    buildsOn: ['softmax-temperature', 'nn-forward-pass', 'quantization'],
    category: 'AI & ML',
    title: 'Knowledge Distillation',
    summary: 'A big teacher model trains a small student with soft probabilities — dark knowledge included.',
    tags: ['distillation', 'compression', 'teacher student', 'DistilBERT', 'small models'],
    module: () => import('./topics/knowledge-distillation.js'),
  },
  {
    id: 'dropout',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'backpropagation', 'random-forest'],
    category: 'AI & ML',
    title: 'Dropout',
    summary: 'Randomly silence neurons during training — an ensemble of sub-networks sharing one set of weights.',
    tags: ['regularization', 'overfitting', 'dropout', 'ensemble', 'training'],
    module: () => import('./topics/dropout.js'),
  },
  {
    id: 'rag-pipeline',
    type: 'visualization',
    buildsOn: ['embeddings-similarity', 'attention', 'kv-cache'],
    category: 'AI & ML',
    title: 'RAG Pipeline',
    summary: 'The full retrieval-augmented loop: embed the question, find nearby documents, ground the answer.',
    tags: ['RAG', 'retrieval', 'vector database', 'hallucination', 'grounding', 'LLM'],
    module: () => import('./topics/rag-pipeline.js'),
  },
  {
    id: 'quantization',
    type: 'visualization',
    buildsOn: ['nn-forward-pass', 'kv-cache'],
    category: 'AI & ML',
    title: 'Quantization',
    summary: 'Squeeze float weights into 8, 4, or 2 bits — watch what survives and what gets lobotomized.',
    tags: ['quantization', 'int4', 'llama.cpp', 'GPTQ', 'compression', 'inference'],
    module: () => import('./topics/quantization.js'),
  },
  {
    id: 'hnsw-search',
    type: 'visualization',
    buildsOn: ['embeddings-similarity', 'graph-bfs', 'skip-list'],
    category: 'AI & ML',
    title: 'HNSW (Vector Search at Scale)',
    summary: 'Greedy-hop a sparse highway layer, then finish in the dense layer — nearest neighbor without a full scan.',
    tags: ['vector database', 'ANN', 'HNSW', 'similarity search', 'pinecone', 'FAISS'],
    module: () => import('./topics/hnsw-search.js'),
  },
  {
    id: 'random-forest',
    type: 'visualization',
    buildsOn: ['binary-search-tree'],
    category: 'AI & ML',
    title: 'Random Forest',
    summary: 'Three different decision trees classify the same animal — then vote. Ensembles beat soloists.',
    tags: ['decision trees', 'ensemble', 'bagging', 'machine learning', 'tabular'],
    module: () => import('./topics/random-forest.js'),
  },
  {
    id: 'attention',
    type: 'visualization',
    buildsOn: ['tokenization-bpe', 'softmax-temperature', 'embeddings-similarity'],
    category: 'AI & ML',
    title: 'Attention Mechanism',
    summary: 'The heart of the Transformer: queries, keys, values, and the softmax heatmap that lets tokens look at each other.',
    tags: ['transformers', 'self-attention', 'softmax', 'QKV', 'LLM'],
    searchText: 'attention is all you need scaled dot product query key value neural network deep learning',
    module: () => import('./topics/attention.js'),
  },
];
