// The single source of truth for everything on the site.
// Adding content = one entry here + one module in src/topics/ (or one HTML
// file in articles/ for type 'article'). Homepage search indexes title,
// summary, category, tags, and searchText.

export const categories = [
  'Data Structures',
  'Sorting',
  'Searching',
  'Concepts',
  'Systems',
  'AI & ML',
  'Papers',
];

// Entries may declare `buildsOn: [ids]` — the simpler ideas they are made of.
// Topic pages render these as "Built from" links, and compute the reverse
// ("Next up") automatically, so complex topics always point back to their
// ingredients and simple topics advertise what they unlock.

export const topics = [
  {
    id: 'linked-list',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Linked List',
    summary: 'A chain of nodes connected by pointers — append, search, and remove by re-linking.',
    tags: ['pointers', 'nodes', 'traversal'],
    module: () => import('./topics/linked-list.js'),
  },
  {
    id: 'stack',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Stack',
    summary: 'Last In, First Out: push and pop from the top, the way undo history works.',
    tags: ['LIFO', 'push', 'pop'],
    module: () => import('./topics/stack.js'),
  },
  {
    id: 'queue',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Queue',
    summary: 'First In, First Out: enqueue at the back, dequeue from the front, like a line at a store.',
    tags: ['FIFO', 'enqueue', 'dequeue'],
    module: () => import('./topics/queue.js'),
  },
  {
    id: 'hash-table',
    type: 'visualization',
    category: 'Data Structures',
    title: 'Hash Table',
    summary: 'Turn a key into a bucket index, handle collisions with probing, rehash as it fills.',
    tags: ['hashing', 'collisions', 'linear probing', 'load factor', 'rehash'],
    module: () => import('./topics/hash-table.js'),
  },
  {
    id: 'binary-search-tree',
    type: 'visualization',
    buildsOn: ['binary-search'],
    category: 'Data Structures',
    title: 'Binary Search Tree',
    summary: 'Smaller values go left, larger go right — so lookups skip half the tree at every node.',
    tags: ['BST', 'tree', 'insert', 'search'],
    module: () => import('./topics/binary-search-tree.js'),
  },
  {
    id: 'insertion-sort',
    type: 'visualization',
    category: 'Sorting',
    title: 'Insertion Sort',
    summary: 'Slide each value left into its place in a growing sorted prefix, like sorting cards in your hand.',
    tags: ['sorting', 'nearly sorted', 'O(n^2)', 'adaptive'],
    module: () => import('./topics/insertion-sort.js'),
  },
  {
    id: 'selection-sort',
    type: 'visualization',
    category: 'Sorting',
    title: 'Selection Sort',
    summary: 'Scan for the smallest remaining value and swap it into place — minimum swaps, maximum scanning.',
    tags: ['sorting', 'minimum', 'O(n^2)'],
    module: () => import('./topics/selection-sort.js'),
  },
  {
    id: 'tree-traversals',
    type: 'visualization',
    buildsOn: ['binary-search-tree', 'recursion', 'queue'],
    category: 'Data Structures',
    title: 'Tree Traversals',
    summary: 'In-order, pre-order, post-order, and level-order — four ways to walk a tree, each with a job.',
    tags: ['BFS', 'DFS', 'in-order', 'level-order', 'tree'],
    module: () => import('./topics/tree-traversals.js'),
  },
  {
    id: 'binary-heap',
    type: 'visualization',
    buildsOn: ['binary-search-tree'],
    category: 'Data Structures',
    title: 'Binary Heap (Priority Queue)',
    summary: 'A tree where every parent beats its children — the maximum is always one peek away.',
    tags: ['priority queue', 'heap', 'bubble up', 'sift down'],
    module: () => import('./topics/binary-heap.js'),
  },
  {
    id: 'bubble-sort',
    type: 'visualization',
    category: 'Sorting',
    title: 'Bubble Sort',
    summary: 'Compare neighbors and swap — the largest value bubbles to the end on every pass.',
    tags: ['sorting', 'swaps', 'O(n^2)'],
    module: () => import('./topics/bubble-sort.js'),
  },
  {
    id: 'merge-sort',
    type: 'visualization',
    buildsOn: ['recursion'],
    category: 'Sorting',
    title: 'Merge Sort',
    summary: 'Split the array in half, sort each half, then merge — divide and conquer at O(n log n).',
    tags: ['sorting', 'divide and conquer', 'stable', 'O(n log n)'],
    module: () => import('./topics/merge-sort.js'),
  },
  {
    id: 'quick-sort',
    type: 'visualization',
    buildsOn: ['recursion'],
    category: 'Sorting',
    title: 'Quick Sort',
    summary: 'Pick a pivot, partition the array around it, recurse — fast in practice and in place.',
    tags: ['sorting', 'pivot', 'partition', 'recursion'],
    module: () => import('./topics/quick-sort.js'),
  },
  {
    id: 'heap-sort',
    type: 'visualization',
    buildsOn: ['binary-heap'],
    category: 'Sorting',
    title: 'Heap Sort',
    summary: 'Build a max-heap inside the array, then repeatedly move the largest value to the end.',
    tags: ['sorting', 'heap', 'sift down', 'O(n log n)'],
    module: () => import('./topics/heap-sort.js'),
  },
  {
    id: 'linear-search',
    type: 'visualization',
    category: 'Searching',
    title: 'Linear Search',
    summary: 'Check every element from left to right — simple, and the best you can do unsorted.',
    tags: ['search', 'O(n)'],
    module: () => import('./topics/linear-search.js'),
  },
  {
    id: 'binary-search',
    type: 'visualization',
    category: 'Searching',
    title: 'Binary Search',
    summary: 'Halve the search range on every comparison — find anything in a sorted array in O(log n).',
    tags: ['search', 'sorted', 'O(log n)', 'divide and conquer'],
    module: () => import('./topics/binary-search.js'),
  },
  {
    id: 'recursion',
    type: 'visualization',
    category: 'Concepts',
    title: 'Recursion',
    summary: 'Watch a function call itself: the call tree for factorial and Fibonacci, opening and returning.',
    tags: ['call stack', 'base case', 'fibonacci', 'factorial'],
    module: () => import('./topics/recursion.js'),
  },
  {
    id: 'big-o-growth',
    type: 'visualization',
    category: 'Concepts',
    title: 'Big-O Growth Rates',
    summary: 'Watch log n, n, n log n, and n² grow apart — the chart that explains why algorithms matter.',
    tags: ['complexity', 'big-o', 'performance', 'scaling'],
    module: () => import('./topics/big-o-growth.js'),
  },
  {
    id: 'memoization',
    type: 'visualization',
    buildsOn: ['recursion', 'hash-table'],
    category: 'Concepts',
    title: 'Memoization (Dynamic Programming)',
    summary: 'Cache every answer the first time you compute it — watch the exponential call tree collapse.',
    tags: ['dynamic programming', 'cache', 'fibonacci', 'optimization'],
    module: () => import('./topics/memoization.js'),
  },
  {
    id: 'gradient-descent',
    type: 'visualization',
    buildsOn: ['big-o-growth'],
    category: 'AI & ML',
    title: 'Gradient Descent',
    summary: 'Follow the slope downhill to minimize loss — the algorithm that trains every neural network.',
    tags: ['training', 'optimization', 'learning rate', 'neural networks', 'loss'],
    module: () => import('./topics/gradient-descent.js'),
  },
  {
    id: 'k-means',
    type: 'visualization',
    category: 'AI & ML',
    title: 'K-Means Clustering',
    summary: 'Group unlabeled points by repeating two moves: assign to nearest centroid, recenter the centroid.',
    tags: ['clustering', 'unsupervised learning', 'centroids'],
    module: () => import('./topics/k-means.js'),
  },
  {
    id: 'tokenization-bpe',
    type: 'visualization',
    category: 'AI & ML',
    title: 'Tokenization (BPE)',
    summary: 'Watch byte-pair encoding merge characters into the tokens LLMs actually read.',
    tags: ['tokens', 'BPE', 'LLM', 'vocabulary', 'strawberry'],
    module: () => import('./topics/tokenization-bpe.js'),
  },
  {
    id: 'softmax-temperature',
    type: 'visualization',
    category: 'AI & ML',
    title: 'Softmax & Temperature',
    summary: 'How raw model scores become probabilities — and how temperature reshapes them from greedy to creative.',
    tags: ['softmax', 'temperature', 'sampling', 'logits', 'LLM'],
    module: () => import('./topics/softmax-temperature.js'),
  },
  {
    id: 'attention',
    type: 'visualization',
    buildsOn: ['tokenization-bpe', 'softmax-temperature'],
    category: 'AI & ML',
    title: 'Attention Mechanism',
    summary: 'The heart of the Transformer: queries, keys, values, and the softmax heatmap that lets tokens look at each other.',
    tags: ['transformers', 'self-attention', 'softmax', 'QKV', 'LLM'],
    searchText: 'attention is all you need scaled dot product query key value neural network deep learning',
    module: () => import('./topics/attention.js'),
  },
];
